name: sepedaan
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  lottie: ^1.2.1
  flutter_hooks: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/lotties/

  fonts:
    - family: Biennale
      fonts:
        - asset: assets/fonts/Biennale-Regular.ttf
          weight: 400
        - asset: assets/fonts/Biennale-Medium.ttf
          weight: 500
        - asset: assets/fonts/Biennale-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Biennale-Bold.ttf
          weight: 700

